baseurl = "//tyk.io/docs/"
languageCode = "en-gb"
title = "Tyk Documentation"
theme = "tykio"
MetaDataFormat = "yaml"

DefaultContentLanguage = "en-gb"

[Languages]

[Languages.en]
	[[languages.en.menu.main]]
		url = "/en-gb/"

[Languages.ko]
	[[languages.de.menu.main]]
		url = "/ko-kr/"

[blackfriday]
 plainIDAnchors = true
 hrefTargetBlank = true